name: docker-ci

on:
  push:
    branches:
      - "main"
    tags:
      - "demo*"
      - "v*"
  pull_request:
      branches:
        - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images:
            ${{ secrets.DOCKERHUB_USERNAME }}/hh-pr-backend
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=match,pattern=demo*,group=0

      - name: Login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build, push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: latest,${{ steps.meta.outputs.tags }}




